version: "3.3" #Versão do arquivo de configuração.
services:
  nginx:
    image: "nginxjar"
    volumes:
      - ./app:/var/www/site
      - ./nginx/logs:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    environment:
      PHP_UPSTREAM_CONTAINER: php-fpm:9000
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
  php-fpm:
    image: "phpjar"
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/site
    networks:
      - backend
networks:
  backend:
  frontend: